---
# Source: helm for kubernetes/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: modern-ux-ui-d840b523          # Service name
  labels:
    app: modern-ux-ui-d840b523
spec:
  type: ClusterIP   # Service type (ClusterIP, NodePort, LoadBalancer)
  selector:
    app: modern-ux-ui-d840b523         # Matches Deployment labels
  ports:
    - protocol: TCP
      port: 3000         # Service port
      targetPort: 3000  # Target container port
